name: 'Build DEB Package'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build DEB Package
        run: |
          sudo bash run.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: '*.deb'
